# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/lsneler/Desktop/Repo/JPEG_conv/raw2jpeg/raw2jpeg.srcs/sources_1/ip/quant_0/quant_0.xci
# IP: The module: 'quant_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/lsneler/Desktop/Repo/JPEG_conv/raw2jpeg/raw2jpeg.srcs/sources_1/ip/quant_0/src/div_gen_0/div_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0}]

# IP: c:/Users/lsneler/Desktop/Repo/JPEG_conv/raw2jpeg/raw2jpeg.srcs/sources_1/ip/quant_0/src/chrominance_quant/chrominance_quant.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==chrominance_quant || ORIG_REF_NAME==chrominance_quant}]

# IP: c:/Users/lsneler/Desktop/Repo/JPEG_conv/raw2jpeg/raw2jpeg.srcs/sources_1/ip/quant_0/src/luminance_quant/luminance_quant.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==luminance_quant || ORIG_REF_NAME==luminance_quant}]

# XDC: c:/Users/lsneler/Desktop/Repo/JPEG_conv/raw2jpeg/raw2jpeg.srcs/sources_1/ip/quant_0/src/chrominance_quant/chrominance_quant_ooc.xdc

# XDC: c:/Users/lsneler/Desktop/Repo/JPEG_conv/raw2jpeg/raw2jpeg.srcs/sources_1/ip/quant_0/src/luminance_quant/luminance_quant_ooc.xdc

# IP: C:/Users/lsneler/Desktop/Repo/JPEG_conv/raw2jpeg/raw2jpeg.srcs/sources_1/ip/quant_0/quant_0.xci
# IP: The module: 'quant_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/lsneler/Desktop/Repo/JPEG_conv/raw2jpeg/raw2jpeg.srcs/sources_1/ip/quant_0/src/div_gen_0/div_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0}]

# IP: c:/Users/lsneler/Desktop/Repo/JPEG_conv/raw2jpeg/raw2jpeg.srcs/sources_1/ip/quant_0/src/chrominance_quant/chrominance_quant.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==chrominance_quant || ORIG_REF_NAME==chrominance_quant}]

# IP: c:/Users/lsneler/Desktop/Repo/JPEG_conv/raw2jpeg/raw2jpeg.srcs/sources_1/ip/quant_0/src/luminance_quant/luminance_quant.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==luminance_quant || ORIG_REF_NAME==luminance_quant}]

# XDC: c:/Users/lsneler/Desktop/Repo/JPEG_conv/raw2jpeg/raw2jpeg.srcs/sources_1/ip/quant_0/src/chrominance_quant/chrominance_quant_ooc.xdc

# XDC: c:/Users/lsneler/Desktop/Repo/JPEG_conv/raw2jpeg/raw2jpeg.srcs/sources_1/ip/quant_0/src/luminance_quant/luminance_quant_ooc.xdc
