# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/lsneler/Desktop/Repository/DCT/DCT/DCT.cache/wt [current_project]
set_property parent.project_path C:/Users/lsneler/Desktop/Repository/DCT/DCT/DCT.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/lsneler/Desktop/Repository/DCT/DCT/DCT.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/lsneler/Desktop/Repository/DCT/DCT/DCT.srcs/sources_1/imports/new/full_adder.v
  C:/Users/lsneler/Desktop/Repository/DCT/DCT/DCT.srcs/sources_1/new/DCT_int.v
  C:/Users/lsneler/Desktop/Repository/DCT/DCT/DCT.srcs/sources_1/new/DCT_fp.v
  C:/Users/lsneler/Desktop/Repository/DCT/DCT/DCT.srcs/sources_1/new/DCT.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/lsneler/Desktop/Repository/DCT/DCT/DCT.srcs/constrs_2/new/constr.xdc
set_property used_in_implementation false [get_files C:/Users/lsneler/Desktop/Repository/DCT/DCT/DCT.srcs/constrs_2/new/constr.xdc]


synth_design -top DCT -part xc7z010clg400-1


write_checkpoint -force -noxdef DCT.dcp

catch { report_utilization -file DCT_utilization_synth.rpt -pb DCT_utilization_synth.pb }
