# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/converter/converter.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==converter || ORIG_REF_NAME==converter}]

# IP: bd/converter/ip/converter_blk_mem_gen_0_0/converter_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==converter_blk_mem_gen_0_0 || ORIG_REF_NAME==converter_blk_mem_gen_0_0}]

# IP: bd/converter/ip/converter_DCT_2D_0_0/converter_DCT_2D_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==converter_DCT_2D_0_0 || ORIG_REF_NAME==converter_DCT_2D_0_0}]

# IP: bd/converter/ip/converter_clk_wiz_0_0/converter_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==converter_clk_wiz_0_0 || ORIG_REF_NAME==converter_clk_wiz_0_0}]

# IP: bd/converter/ip/converter_xlconstant_0_0/converter_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==converter_xlconstant_0_0 || ORIG_REF_NAME==converter_xlconstant_0_0}]

# IP: bd/converter/ip/converter_quant_0_0/converter_quant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==converter_quant_0_0 || ORIG_REF_NAME==converter_quant_0_0}]

# IP: bd/converter/ip/converter_controller_0_0/converter_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==converter_controller_0_0 || ORIG_REF_NAME==converter_controller_0_0}]

# IP: bd/converter/ip/converter_AXILiteToBRAMIntf_0_0/converter_AXILiteToBRAMIntf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==converter_AXILiteToBRAMIntf_0_0 || ORIG_REF_NAME==converter_AXILiteToBRAMIntf_0_0}]

# IP: bd/converter/ip/converter_blk_mem_gen_1_1/converter_blk_mem_gen_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==converter_blk_mem_gen_1_1 || ORIG_REF_NAME==converter_blk_mem_gen_1_1}]

# XDC: bd/converter/converter_ooc.xdc
