# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/AxiLiteZynqBRAMDemo2/ZYBO_Master.xdc

# XDC: new/top.xdc

# Block Designs: bd/converter/converter.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==converter || ORIG_REF_NAME==converter}]

# IP: bd/converter/ip/converter_blk_mem_gen_0_0/converter_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==converter_blk_mem_gen_0_0 || ORIG_REF_NAME==converter_blk_mem_gen_0_0}]

# IP: bd/converter/ip/converter_DCT_2D_0_0/converter_DCT_2D_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==converter_DCT_2D_0_0 || ORIG_REF_NAME==converter_DCT_2D_0_0}]

# IP: bd/converter/ip/converter_quant_0_0/converter_quant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==converter_quant_0_0 || ORIG_REF_NAME==converter_quant_0_0}]

# IP: bd/converter/ip/converter_controller_0_0/converter_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==converter_controller_0_0 || ORIG_REF_NAME==converter_controller_0_0}]

# IP: bd/converter/ip/converter_AXILiteToBRAMIntf_0_0/converter_AXILiteToBRAMIntf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==converter_AXILiteToBRAMIntf_0_0 || ORIG_REF_NAME==converter_AXILiteToBRAMIntf_0_0}]

# IP: bd/converter/ip/converter_blk_mem_gen_1_1/converter_blk_mem_gen_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==converter_blk_mem_gen_1_1 || ORIG_REF_NAME==converter_blk_mem_gen_1_1}]

# IP: bd/converter/ip/converter_processing_system7_0_0/converter_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==converter_processing_system7_0_0 || ORIG_REF_NAME==converter_processing_system7_0_0}]

# IP: bd/converter/ip/converter_ps7_0_axi_periph_0/converter_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==converter_ps7_0_axi_periph_0 || ORIG_REF_NAME==converter_ps7_0_axi_periph_0}]

# IP: bd/converter/ip/converter_rst_ps7_0_50M_0/converter_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==converter_rst_ps7_0_50M_0 || ORIG_REF_NAME==converter_rst_ps7_0_50M_0}]

# IP: bd/converter/ip/converter_system_ila_0_0/converter_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==converter_system_ila_0_0 || ORIG_REF_NAME==converter_system_ila_0_0}]

# IP: bd/converter/ip/converter_auto_pc_0/converter_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==converter_auto_pc_0 || ORIG_REF_NAME==converter_auto_pc_0}]

# XDC: bd/converter/converter_ooc.xdc
