# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/lsneler/Desktop/Repo/JPEG_conv/component_modules/RLE/RLE.cache/wt [current_project]
set_property parent.project_path C:/Users/lsneler/Desktop/Repo/JPEG_conv/component_modules/RLE/RLE.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths c:/Users/lsneler/Desktop/Repo/JPEG_conv/IP_Core_repo/RLE [current_project]
set_property ip_output_repo c:/Users/lsneler/Desktop/Repo/JPEG_conv/component_modules/RLE/RLE.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/lsneler/Desktop/Repo/JPEG_conv/component_modules/RLE/RLE.ip_user_files/inputData.coe
read_verilog -library xil_defaultlib C:/Users/lsneler/Desktop/Repo/JPEG_conv/component_modules/RLE/RLE.srcs/sources_1/new/RLE.v
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top RLE -part xc7z010clg400-1


write_checkpoint -force -noxdef RLE.dcp

catch { report_utilization -file RLE_utilization_synth.rpt -pb RLE_utilization_synth.pb }
