# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/lsneler/Desktop/Repo/JPEG_conv/raw2jpeg/raw2jpeg.srcs/sources_1/bd/converter/ip/converter_zig_zag_0_0/converter_zig_zag_0_0.xci
# IP: The module: 'converter_zig_zag_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/lsneler/Desktop/Repo/JPEG_conv/raw2jpeg/raw2jpeg.srcs/sources_1/bd/converter/ip/converter_zig_zag_0_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0}]

# XDC: c:/Users/lsneler/Desktop/Repo/JPEG_conv/raw2jpeg/raw2jpeg.srcs/sources_1/bd/converter/ip/converter_zig_zag_0_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# IP: c:/Users/lsneler/Desktop/Repo/JPEG_conv/raw2jpeg/raw2jpeg.srcs/sources_1/bd/converter/ip/converter_zig_zag_0_0/converter_zig_zag_0_0.xci
# IP: The module: 'converter_zig_zag_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/lsneler/Desktop/Repo/JPEG_conv/raw2jpeg/raw2jpeg.srcs/sources_1/bd/converter/ip/converter_zig_zag_0_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0}]

# XDC: c:/Users/lsneler/Desktop/Repo/JPEG_conv/raw2jpeg/raw2jpeg.srcs/sources_1/bd/converter/ip/converter_zig_zag_0_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
