# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/lsneler/Desktop/Repository/JPEG_conversion/quantizator/quantizator.srcs/sources_1/ip/luminance_quant/luminance_quant.xci
# IP: The module: 'luminance_quant' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lsneler/Desktop/Repository/JPEG_conversion/quantizator/quantizator.srcs/sources_1/ip/luminance_quant/luminance_quant_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'luminance_quant'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/lsneler/Desktop/Repository/JPEG_conversion/quantizator/quantizator.srcs/sources_1/ip/luminance_quant/luminance_quant.xci
# IP: The module: 'luminance_quant' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lsneler/Desktop/Repository/JPEG_conversion/quantizator/quantizator.srcs/sources_1/ip/luminance_quant/luminance_quant_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'luminance_quant'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
